### ISSUE TITLE
Didn't know any other way to reach ypu

### ISSUE THREAD

**Issue by oneEyedSunday** [brianalois/angular5_jwt#1]
i'm enthralled by your writing, been following the jwt with node tutorials, would lik eto have the link to the article i'm assuming this repo is part of. Thanks

**Comment by brianjakob** [comment]
You can contact me at brian@orangetech.io 
I havnt written an article yet for this one but I will soon! Glad to know you like them.

**Comment by oneEyedSunday** [comment]
Ok, I'd be on the lookout, you'd be posting on medium or codeburst?
